FROM node:20-alpine AS build
WORKDIR /app

# Build args
ARG PUBLIC_SANITY_PROJECT_ID
ARG PUBLIC_SANITY_DATASET
ARG PUBLIC_SANITY_API_VERSION
ARG PUBLIC_SITE_ID
ARG PUBLIC_API_BASE

# Set env vars
ENV PUBLIC_SANITY_PROJECT_ID=$PUBLIC_SANITY_PROJECT_ID
ENV PUBLIC_SANITY_DATASET=$PUBLIC_SANITY_DATASET
ENV PUBLIC_SANITY_API_VERSION=$PUBLIC_SANITY_API_VERSION
ENV PUBLIC_SITE_ID=$PUBLIC_SITE_ID
ENV PUBLIC_API_BASE=$PUBLIC_API_BASE

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./
ENV HOST=0.0.0.0
ENV PORT=8080
EXPOSE 8080
CMD ["node", "./dist/server/entry.mjs"]
